makefile:

all:
	gcc  ./Lexer/lexer.c ./Lexer/delimlexer.c ./Lexer/helper.c ./Lexer/oplexer.c ./Lexer/wordlexer.c ./Lexer/constlexer.c \
	./Parser/parser.c ./Parser/expressParser.c ./Parser/helper.c  ./Parser/symbolParser.c ./Parser/compositeParser.c -o nova

clean:
	rm nova